server:
  port: 8787

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/tk_test?characterEncoding=UTF-8&serverTimezone=UTC
      username: timothy
      password: Timothy@2020
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: timothy-pool

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true,
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

#mybatis:
#  type-aliases-package: com.timothy20.TKWebCrawler.dto
#  mapper-locations: mybatis/**/*.xml